# Generated by Django 6.0.1 on 2026-02-02 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
